### ISSUE TITLE
Style Contradiction

### ISSUE THREAD

**Issue by jspies** [bypasslane/ruby-style-guide#2]
This is listed as bad

def meth "stuff"; end

But this is good

"Prefer a single-line format for class definitions with no body."

Not sure I agree with that. Class.new() syntax has to be completely deleted and rewritten to be extended or maintained

**Comment by teubanks** [comment]
I agree with this. I'd rather not have single line class definitions even if the class has no body

**Comment by jspies** [comment]
necro!
